/* You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"                         */

import java.util.*;
public class FindTheDifference{
    public static char findTheDifference(String s, String t){
        char[] res1 = s.toCharArray();
        char[] res2 = t.toCharArray();
        Arrays.sort(res1);
        Arrays.sort(res2);

        for(int i=0; i<s.length(); i++){
            if(res1[i] != res2[i]){
                return res2[i];
            }
        }
        return res2[s.length()];
    }
    public static void main(String[] args){
        String s = "abcd";
        String t = "abcde";
        System.out.println(findTheDifference(s, t));
    }
}